import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/Header/HeaderWrapper";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

const lato = Lato({
   variable: "--font-lato",
   subsets: ["latin"],
   weight: "400",
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${lato.variable}`}>
            <HeaderWrapper />
            <main>{children}</main>
         </body>
      </html>
   );
}
